
title: "Lauris Jullien"
author: "Lauris Jullien"
description: "Thoughts & Articles" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "lauris.jullien@telecom-paristech.org"
linkedin_username: "laurisjullien"
theme: minima
